apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: quarkus-native  
spec:
  tasks:
    - name: git-clone
      params:
        - name: CRT_FILENAME
          value: ca-bundle.crt
        - name: HTTP_PROXY
          value: ''
        - name: HTTPS_PROXY
          value: ''
        - name: NO_PROXY
          value: ''
        - name: SUBDIRECTORY
          value: ''
        - name: USER_HOME
          value: /home/git
        - name: DELETE_EXISTING
          value: 'true'
        - name: VERBOSE
          value: 'false'
        - name: SSL_VERIFY
          value: 'true'
        - name: URL
          value: 'https://github.com/marcoklaassen/simple-quarkus-function'
        - name: REVISION
          value: main
        - name: REFSPEC
          value: ''
        - name: SUBMODULES
          value: 'true'
        - name: DEPTH
          value: '1'
        - name: SPARSE_CHECKOUT_DIRECTORIES
          value: ''
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: output
          workspace: source
    - name: build-native-executable
      runAfter:
        - git-clone
      taskSpec:
        metadata: {}
        spec: null
        steps:
          - command:
              - ./mvnw
              - package
              - '-Pnative'
            computeResources: {}
            image: 'quay.io/quarkus/ubi-quarkus-mandrel-builder-image:24.1.2.0-Final-java23-2025-03-09'
            name: build-executable
            workingDir: /workspace/source
        workspaces:
          - description: the source code
            name: source
      workspaces:
        - name: source
          workspace: source
    - name: buildah
      params:
        - name: IMAGE
          value: 'image-registry.openshift-image-registry.svc:5000/streaming-demo/simple-quarkus-function'
        - name: DOCKERFILE
          value: ./src/main/docker/Dockerfile.native-micro
        - name: BUILD_ARGS
          value: []
        - name: CONTEXT
          value: .
        - name: STORAGE_DRIVER
          value: vfs
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: ''
        - name: PUSH_EXTRA_ARGS
          value: ''
        - name: SKIP_PUSH
          value: 'false'
        - name: TLS_VERIFY
          value: 'true'
        - name: VERBOSE
          value: 'false'
      runAfter:
        - build-native-executable
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: buildah
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: source
          workspace: source
  workspaces:
    - name: source
